name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tika-proxy:$(date +%s) --tag tika-proxy:latest
    - name: Upload the Docker image
      run: |
        docker push ghcr.io/tika-proxy/tika-proxy:latest 
        docker push ghcr.io/tika-proxy/tika-proxy:$(date +%s)
