name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG_LATEST: ghcr.io/tika-proxy/tika-proxy:latest
  TAG_DATE: ghcr.io/tika-proxy/tika-proxy:$(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${TAG_DATE} -t ${TAG_LATEST}
    - name: Upload the Docker image
      run: |
        docker push $TAG_DATE
        docker push $TAG_LATEST
